In [1]:
#numpy The fundamental package for scientific computing with Python
# powerful n dimensional array , Numerical computing tools , open source

In [ ]:
# arrays - homogenous ,index
# array can be one dimention and n - dimension
# we can easily perform math operations on array

In [2]:
l=[1,2,3,4]
l1=[]
for item in l:
  l1.append(item*2)

print(l1)


[2, 4, 6, 8]


In [3]:
#python -m pip install numpy
import numpy as np


In [5]:
arr=np.array([10,20,30,40])
print(type(arr))
print(arr)
print(arr**2)

<class 'numpy.ndarray'>
[10 20 30 40]
[ 100  400  900 1600]


In [8]:
print('dimension of array',arr.ndim)
print('data type of item of array',arr.dtype)
print('size of item of array',arr.itemsize)


dimension of array 1
data type of item of array int64
size of item of array 8


In [11]:
arr=np.array([10,20,30,40],dtype=np.float32)
print(type(arr))
print(arr)
print('data type of item of array',arr.dtype)
print('size of item of array',arr.itemsize)
print('length of array',len(arr))
print('get shape of array',arr.shape)

<class 'numpy.ndarray'>
[10. 20. 30. 40.]
data type of item of array float32
size of item of array 4
length of array 4
get shape of array (4,)


In [12]:
mat=np.array([[10,20,30],[40,50,60],[70,80,90]])
print(mat)

[[10 20 30]
 [40 50 60]
 [70 80 90]]


In [14]:
print('length of array',len(mat))
print('get shape of array',mat.shape) # shape will return no of rows and columns of an array
print('dimension of array',mat.ndim)

length of array 3
get shape of array (3, 3)
dimension of array 2


In [16]:
z=np.zeros((2,4),dtype=np.int32)
print('Zero array \n',z)

Zero array 
 [[0 0 0 0]
 [0 0 0 0]]


In [17]:
o=np.ones((4,4),dtype=np.int32)
print('ones array \n',o)

ones array 
 [[1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]]


In [19]:
n=int(input('enter no'))
print(o*n)

enter no15
[[15 15 15 15]
 [15 15 15 15]
 [15 15 15 15]
 [15 15 15 15]]


In [21]:
n=int(input('enter no'))
f=np.full((3,3),n)  #(shape,valuetofill)
print('filled array \n',f)

enter no5
filled array 
 [[5 5 5]
 [5 5 5]
 [5 5 5]]


In [23]:
#identical matrix
identical = np.eye(4,dtype=np.int32)
print(identical)

[[1 0 0 0]
 [0 1 0 0]
 [0 0 1 0]
 [0 0 0 1]]


In [24]:
randomarr=np.random.random((3,2))
print('Random array \n',randomarr)

Random array 
 [[0.12356519 0.48136534]
 [0.11368573 0.75587341]
 [0.46655163 0.92762318]]


In [28]:
randomintarr=np.random.randint(low=10,high=30,size=(4,4)) # randint(start, end ,size)
print(randomintarr)

[[28 25 18 25]
 [29 19 20 24]
 [26 18 23 23]
 [12 29 26 16]]


In [29]:
mat=np.array([[10,20,30],[40,50,60],[70,80,90]])
print(mat)

[[10 20 30]
 [40 50 60]
 [70 80 90]]


In [30]:
# transpose array - convert rows into columns and columns into rows
tmat=mat.T
print('Transpose array \n',tmat)

Transpose array 
 [[10 40 70]
 [20 50 80]
 [30 60 90]]


In [31]:
tmat1=mat.transpose()
print('Transpose array \n',tmat1)

Transpose array 
 [[10 40 70]
 [20 50 80]
 [30 60 90]]


In [32]:
#reshape and resize an array
mat=np.array([[10,20,30],[40,50,60],[70,80,90]])
print(mat)

[[10 20 30]
 [40 50 60]
 [70 80 90]]


In [44]:
#reshape() will change the shape of array.
#in reshape no of elements of array  should be same
# original array is not change, new array will be created
rarr=np.reshape(mat,(1,9))   # np.reshape(arr,newshape) newshape must same total no elements as orignal shape
print('reshape array \n',rarr)
print('shape of array',rarr.shape)
print('dimension is ',rarr.ndim)

reshape array 
 [[10 20 30 40 50 60 70 80 90]]
shape of array (1, 9)
dimension is  2


In [34]:
rarr=np.reshape(mat,(9,1))   # np.reshape(arr,newshape) newshape must same total no elements as orignal shape
print('reshape array \n',rarr)

reshape array 
 [[10]
 [20]
 [30]
 [40]
 [50]
 [60]
 [70]
 [80]
 [90]]


In [38]:
#resize() resize array
resizedarr=np.resize(mat,(5,5))
print('Resized array \n',resizedarr)


Resized array 
 [[10 20 30 40 50]
 [60 70 80 90 10]
 [20 30 40 50 60]
 [70 80 90 10 20]
 [30 40 50 60 70]]


In [39]:
resizedarr=np.resize(mat,(2,2))
print('Resized array \n',resizedarr)

Resized array 
 [[10 20]
 [30 40]]


In [43]:
#convert array in 1 dim
onedimarr=mat.ravel() # Return a flattened array.
print(onedimarr)
print('shape is',onedimarr.shape)
print(onedimarr.ndim)

[10 20 30 40 50 60 70 80 90]
shape is (9,)
1


In [45]:
#arange(start,end,step) generate 1 dim array in a given range  end is excluded
arr =np.arange(10,20,2)
print(arr)

[10 12 14 16 18]


In [46]:
arr =np.arange(100,90,-1)
print(arr)

[100  99  98  97  96  95  94  93  92  91]


In [47]:
arr=arr.reshape((5,2))
print(arr)

[[100  99]
 [ 98  97]
 [ 96  95]
 [ 94  93]
 [ 92  91]]


In [52]:
# access value  arrayname[index], arrayname[row][column] ,arr[x][y][z]
print('value at 0 row 0 column',arr[0][0])
print(arr[3][1])
#print(arr[6][3]) IndexError: index 6 is out of bounds for axis 0 with size 5

value at 0 row 0 column 100
93


In [54]:
# updatevalue arrayname[index]=value , arr[row][column]=value
arr[0][0]=66
print(arr)

[[66 99]
 [98 97]
 [96 95]
 [94 93]
 [92 91]]


In [55]:
mat

array([[10, 20, 30],
       [40, 50, 60],
       [70, 80, 90]])

In [63]:
mat1=np.resize(mat,(10,10))
mat1

array([[10, 20, 30, 40, 50, 60, 70, 80, 90, 10],
       [20, 30, 40, 50, 60, 70, 80, 90, 10, 20],
       [30, 40, 50, 60, 70, 80, 90, 10, 20, 30],
       [40, 50, 60, 70, 80, 90, 10, 20, 30, 40],
       [50, 60, 70, 80, 90, 10, 20, 30, 40, 50],
       [60, 70, 80, 90, 10, 20, 30, 40, 50, 60],
       [70, 80, 90, 10, 20, 30, 40, 50, 60, 70],
       [80, 90, 10, 20, 30, 40, 50, 60, 70, 80],
       [90, 10, 20, 30, 40, 50, 60, 70, 80, 90],
       [10, 20, 30, 40, 50, 60, 70, 80, 90, 10]])

In [64]:
rshape=np.reshape(mat1,(1,-1)) # -1 create  no of columns  that is equal to tatal item in array
print(rshape)

[[10 20 30 40 50 60 70 80 90 10 20 30 40 50 60 70 80 90 10 20 30 40 50 60
  70 80 90 10 20 30 40 50 60 70 80 90 10 20 30 40 50 60 70 80 90 10 20 30
  40 50 60 70 80 90 10 20 30 40 50 60 70 80 90 10 20 30 40 50 60 70 80 90
  10 20 30 40 50 60 70 80 90 10 20 30 40 50 60 70 80 90 10 20 30 40 50 60
  70 80 90 10]]


In [65]:
rshape=np.reshape(mat1,(-1,1)) # -1 create  no of rows  that is equal to tatal item in array
print(rshape)

[[10]
 [20]
 [30]
 [40]
 [50]
 [60]
 [70]
 [80]
 [90]
 [10]
 [20]
 [30]
 [40]
 [50]
 [60]
 [70]
 [80]
 [90]
 [10]
 [20]
 [30]
 [40]
 [50]
 [60]
 [70]
 [80]
 [90]
 [10]
 [20]
 [30]
 [40]
 [50]
 [60]
 [70]
 [80]
 [90]
 [10]
 [20]
 [30]
 [40]
 [50]
 [60]
 [70]
 [80]
 [90]
 [10]
 [20]
 [30]
 [40]
 [50]
 [60]
 [70]
 [80]
 [90]
 [10]
 [20]
 [30]
 [40]
 [50]
 [60]
 [70]
 [80]
 [90]
 [10]
 [20]
 [30]
 [40]
 [50]
 [60]
 [70]
 [80]
 [90]
 [10]
 [20]
 [30]
 [40]
 [50]
 [60]
 [70]
 [80]
 [90]
 [10]
 [20]
 [30]
 [40]
 [50]
 [60]
 [70]
 [80]
 [90]
 [10]
 [20]
 [30]
 [40]
 [50]
 [60]
 [70]
 [80]
 [90]
 [10]]
